### ISSUE TITLE
-B does not subset regions

### ISSUE THREAD

**Issue by EMossotto** [tflati/reditools2.0#2]
When running reditools.py the -B option is not having an effect on the regions scanned.

My test bed file (gria.bed) contains only one region: chr4 157336722 157336723 (tab separated).
Reditools does process the bed file  but not implements it and starts outputting whole transcriptome changes
```
Loading target positions from file gria.bed (region:None)
### TARGET POSITIONS ###
Counter({'chr4': 2})
('TOTAL POSITIONS:', 2)
[INFO] Fetching data from bam subset.bam
[INFO] Narrowing REDItools to region None
Opening bamfile within region=None
[INFO] REFERENCE NAME=chr1 (2020-08-20 12:24:03.719745)	[00:00:01]
```

**Comment by tud03125** [comment]
@EMossotto I'm also having this similar issue. Did you get to figure it out?
